import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'roman_ur' | 'ur' | 'ar' | 'zh' | 'fr' | 'es';

interface Translations {
  [key: string]: { [key: string]: string };
}

const translations: Translations = {
  en: {
    dashboard: 'Dashboard',
    accounting: 'Accounting',
    chartOfAccounts: 'Chart of Accounts',
    journalEntry: 'Journal General',
    generalLedger: 'General Ledger',
    bankReconciliation: 'Bank Reconciliation',
    business: 'Business',
    sales: 'Sales',
    purchases: 'Purchases',
    inventory: 'Inventory',
    warehouses: 'Warehouses',
    expenses: 'Expenses',
    eCommercePayouts: 'E-Commerce Payouts',
    reports: 'Reports',
    system: 'System',
    settings: 'Settings',
    logout: 'Logout',
    aiAssistant: 'AI Assistant',
    settingsPanel: 'Settings Panel',
    userProfileNode: 'User Profile Node',
    fullSignatureName: 'Full Signature Name',
    accessAuthKey: 'Access Authorization Key',
    updateProfile: 'Update Profile',
    interfaceLanguage: 'Interface Language',
    selectLanguageDesc: 'Select preferred operational system language:',
    askAiPlaceholder: 'Ask AI financial questions or request accounting insights...',
    clearChat: 'Clear Chat',
    aiDisclaimer: 'AI responses are generated based on active ledger data & financial parameters.',
    manageCompanyFeatures: 'Manage & Edit Company Features',
    clickEditFeaturesDesc: 'Click "Edit Features" next to any registered company to turn modules ON/OFF',
    companyName: 'Company Name',
    companyId: 'Company ID',
    actionOptions: 'Action Options',
    editFeatures: 'Edit Features',
    enterpriseControlCenter: 'Enterprise Multi-Company Control Centre',
    enterpriseControlDesc: 'Configure ecosystem access signatures, core numbering sequences, and tenant user boundaries',
    companyProfileTitle: 'Company Profile Title',
    officialContactEmail: 'Official Contact Email',
    taxNodeId: 'Tax Node / NTN ID (Optional)',
    reportingBaseCurrency: 'Reporting / Base Currency',
    invoiceFormatPrefix: 'Invoice Format Prefix',
    initialNextIndex: 'Initial Next Index Sequence',
    ecosystemCapabilities: 'Ecosystem Capabilities Allocations Configuration',
    bindInitialStaff: 'Bind Initial Workspace Staff Member Identity (Optional)',
    staffDisplayName: 'Staff Display Name',
    uniqueUsernameHandle: 'Unique Username Handle',
    securityLoginPassword: 'Security Login Password',
    scopeLockedRole: 'Scope Locked Role Assignment',
    executeLaunchCluster: 'Execute & Launch Corporate Cluster',
    deployingCluster: 'Deploying Decentralized Nodes...',
    userWorkspaceTerminal: 'User Workspace Management Terminal',
    supervisingAllEmployees: 'Supervising every active deployment employee across all corporate entities',
    displayingScopeStaff: 'Displaying staff members mapped exclusively inside',
    companyContextNode: 'Company Context Node',
    staffMemberIdentity: 'Staff Member Identity',
    securityAccessPassword: 'Security Access Password',
    workspaceBoundaryNode: 'Ecosystem Workspace Boundary Locking Node',
    scopePermissions: 'Scope Permissions',
    cascadeDeletionZone: 'Infrastructure Cascade Deletion Zone',
    deletionZoneDesc: 'Irreversible structural cloud cluster cleanups',
    selectCorporateTargetErase: 'Select Corporate Target To Erase From Infrastructure Cloud',
    eraseCorporateProfileNode: 'Erase Corporate Profile Node',
    wipingNode: 'Wiping Node...'
  },
  fr: {
    dashboard: 'Tableau de bord',
    accounting: 'Comptabilité',
    chartOfAccounts: 'Plan comptable',
    journalEntry: 'Journal Général',
    generalLedger: 'Grand Livre',
    bankReconciliation: 'Rapprochement Bancaire',
    business: 'Entreprise',
    sales: 'Ventes',
    purchases: 'Achats',
    inventory: 'Inventaire',
    warehouses: 'Entrepôts',
    expenses: 'Dépenses',
    eCommercePayouts: 'Paiements E-Commerce',
    reports: 'Rapports',
    system: 'Système',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    aiAssistant: 'Assistant IA',
    settingsPanel: 'Panneau de Configuration',
    userProfileNode: 'Profil Utilisateur',
    fullSignatureName: 'Nom Complet',
    accessAuthKey: "Clé d'autorisation",
    updateProfile: 'Mettre à jour le profil',
    interfaceLanguage: "Langue de l'interface",
    selectLanguageDesc: 'Sélectionnez la langue opérationnelle préférée :',
    askAiPlaceholder: 'Posez des questions financières ou demandez des analyses comptables...',
    clearChat: 'Effacer la discussion',
    aiDisclaimer: 'Les réponses sont générées à partir des données comptables actives.',
    manageCompanyFeatures: 'Gérer et modifier les fonctionnalités de l’entreprise',
    clickEditFeaturesDesc: 'Cliquez sur "Modifier les fonctionnalités" à côté de n’importe quelle entreprise enregistrée',
    companyName: "Nom de l'entreprise",
    companyId: "ID d'entreprise",
    actionOptions: "Options d'action",
    editFeatures: 'Modifier les fonctionnalités',
    enterpriseControlCenter: 'Centre de contrôle multi-entreprises',
    enterpriseControlDesc: 'Configurez les accès, le séquençage et les limites des utilisateurs',
    companyProfileTitle: "Titre du profil d'entreprise",
    officialContactEmail: 'E-mail de contact officiel',
    taxNodeId: 'ID fiscal / NTN (Optionnel)',
    reportingBaseCurrency: 'Devise de référence',
    invoiceFormatPrefix: 'Préfixe de facture',
    initialNextIndex: 'Séquence d’index suivante',
    ecosystemCapabilities: 'Configuration des fonctionnalités de l’écosystème',
    bindInitialStaff: 'Lier l’identité du personnel initial (Optionnel)',
    staffDisplayName: 'Nom du personnel',
    uniqueUsernameHandle: 'Nom d’utilisateur unique',
    securityLoginPassword: 'Mot de passe de sécurité',
    scopeLockedRole: 'Rôle verrouillé',
    executeLaunchCluster: 'Exécuter et lancer le cluster',
    deployingCluster: 'Déploiement en cours...',
    userWorkspaceTerminal: 'Terminal de gestion des utilisateurs',
    supervisingAllEmployees: 'Supervision de tous les employés actifs',
    displayingScopeStaff: 'Affichage des membres du personnel de',
    companyContextNode: "Contexte d'entreprise",
    staffMemberIdentity: 'Identité du personnel',
    securityAccessPassword: 'Mot de passe d’accès',
    workspaceBoundaryNode: 'Nœud de verrouillage',
    scopePermissions: 'Autorisations',
    cascadeDeletionZone: 'Zone de suppression d’infrastructure',
    deletionZoneDesc: 'Nettoyage irréversible du cloud',
    selectCorporateTargetErase: 'Sélectionner la cible à effacer',
    eraseCorporateProfileNode: 'Effacer le profil d’entreprise',
    wipingNode: 'Suppression en cours...'
  },
  ur: {
    dashboard: 'ڈیش بورڈ',
    accounting: 'اکاؤنٹنگ',
    chartOfAccounts: 'کھاتوں کا خاکہ',
    journalEntry: 'روزنامچہ جریدہ',
    generalLedger: 'جنرل لیجر',
    bankReconciliation: 'بینک مطابقت',
    business: 'کاروبار',
    sales: 'فروخت',
    purchases: 'خریداری',
    inventory: 'انوینٹری',
    warehouses: 'گودام',
    expenses: 'اخراجات',
    eCommercePayouts: 'ای کامرس ادائیگی',
    reports: 'رپورٹس',
    system: 'سسٹم',
    settings: 'سیٹنگز',
    logout: 'لاگ آؤٹ',
    aiAssistant: 'اے آئی اسسٹنٹ',
    settingsPanel: 'سیٹنگز پینل',
    userProfileNode: 'صارف کی پروفائل',
    fullSignatureName: 'پورا نام',
    accessAuthKey: 'پاس ورڈ کی',
    updateProfile: 'پروفائل اپ ڈیٹ کریں',
    interfaceLanguage: 'سسٹم کی زبان',
    selectLanguageDesc: 'اپنی پسندیدہ زبان کا انتخاب کریں:',
    askAiPlaceholder: 'مالیاتی سوالات پوچھیں یا اکاؤنٹنگ رپورٹ حاصل کریں...',
    clearChat: 'چیٹ صاف کریں',
    aiDisclaimer: 'اے آئی کے جوابات آپ کے کھاتوں کی بنیاد پر تیار کیے جاتے ہیں۔',
    manageCompanyFeatures: 'کمپنی کے فیچرز تبدیل کریں',
    clickEditFeaturesDesc: 'فیچرز آن یا آف کرنے کے لیے ایڈٹ فیچرز پر کلک کریں',
    companyName: 'کمپنی کا نام',
    companyId: 'کمپنی آئی ڈی',
    actionOptions: 'کارروائی کے آپشنز',
    editFeatures: 'فیچرز ایڈٹ کریں',
    enterpriseControlCenter: 'ملٹی کمپنی کنٹرول سینٹر',
    enterpriseControlDesc: 'تمام کمپنیوں کے سیکورٹی اور صارف کے حقوق سیٹ کریں',
    companyProfileTitle: 'کمپنی کا نام',
    officialContactEmail: 'سرکاری ای میل',
    taxNodeId: 'ٹیکس یا این ٹی این نمبر (آپشنل)',
    reportingBaseCurrency: 'بنیادی کرنسی',
    invoiceFormatPrefix: 'انوائس پریفیکس',
    initialNextIndex: 'انوائس نمبر کا آغاز',
    ecosystemCapabilities: 'سسٹم فیچرز کی سیٹنگز',
    bindInitialStaff: 'ابتدائی سٹاف ممبر شامل کریں (آپشنل)',
    staffDisplayName: 'سٹاف کا نام',
    uniqueUsernameHandle: 'یوزر نیم',
    securityLoginPassword: 'لاگ ان پاس ورڈ',
    scopeLockedRole: 'عہدہ / رول',
    executeLaunchCluster: 'نئی کمپنی بنائیں',
    deployingCluster: 'کمپنی بنائی جا رہی ہے...',
    userWorkspaceTerminal: 'صارفین کی تفصیلات',
    supervisingAllEmployees: 'تمام کمپنیوں کے ملازمین کی نگرانی',
    displayingScopeStaff: 'اس کمپنی کے ملازمین:',
    companyContextNode: 'کمپنی نوڈ',
    staffMemberIdentity: 'ملازم کی شناخت',
    securityAccessPassword: 'لاگ ان پاس ورڈ',
    workspaceBoundaryNode: 'لاکنگ نوڈ',
    scopePermissions: 'اجازت نامہ',
    cascadeDeletionZone: 'ڈیلیٹ کرنے کا علاقہ',
    deletionZoneDesc: 'کمپنی کا تمام ڈیٹا ہمیشہ کے لیے ختم کریں',
    selectCorporateTargetErase: 'ختم کرنے کے لیے کمپنی منتخب کریں',
    eraseCorporateProfileNode: 'کمپنی ختم کریں',
    wipingNode: 'ڈیٹا ڈیلیٹ ہو رہا ہے...'
  },
  roman_ur: {
    dashboard: 'Dashboard',
    accounting: 'Accounting',
    chartOfAccounts: 'Khataon Ka Khaka',
    journalEntry: 'Roznamcha General',
    generalLedger: 'General Ledger',
    bankReconciliation: 'Bank Reconciliation',
    business: 'Karobar',
    sales: 'Farokht (Sales)',
    purchases: 'Kharidari (Purchases)',
    inventory: 'Inventory Stock',
    warehouses: 'Godam (Warehouses)',
    expenses: 'Ikhrajat (Expenses)',
    eCommercePayouts: 'E-Commerce Payouts',
    reports: 'Reports',
    system: 'System',
    settings: 'Settings',
    logout: 'Logout',
    aiAssistant: 'AI Assistant',
    settingsPanel: 'Settings Panel',
    userProfileNode: 'User Profile Node',
    fullSignatureName: 'Poora Naam',
    accessAuthKey: 'Password Key',
    updateProfile: 'Profile Update Karen',
    interfaceLanguage: 'System Ki Language',
    selectLanguageDesc: 'Apni pasandida zaban select karen:',
    askAiPlaceholder: 'Maliati sawal poochen ya accounting insight mangen...',
    clearChat: 'Chat Saaf Karen',
    aiDisclaimer: 'AI jawabat aap ke live ledger data par mabni hain.',
    manageCompanyFeatures: 'Company Features Manage & Edit Karen',
    clickEditFeaturesDesc: 'Modules ON/OFF karne ke liye Edit Features par click karen',
    companyName: 'Company Name',
    companyId: 'Company ID',
    actionOptions: 'Action Options',
    editFeatures: 'Edit Features',
    enterpriseControlCenter: 'Enterprise Multi-Company Control Centre',
    enterpriseControlDesc: 'Company access aur numbering sequences configure karen',
    companyProfileTitle: 'Company Profile Title',
    officialContactEmail: 'Official Email',
    taxNodeId: 'Tax / NTN ID (Optional)',
    reportingBaseCurrency: 'Reporting Currency',
    invoiceFormatPrefix: 'Invoice Prefix',
    initialNextIndex: 'Initial Next Index',
    ecosystemCapabilities: 'System Capabilities Configuration',
    bindInitialStaff: 'Initial Staff Member Add Karen (Optional)',
    staffDisplayName: 'Staff Display Name',
    uniqueUsernameHandle: 'Username Handle',
    securityLoginPassword: 'Login Password',
    scopeLockedRole: 'Scope Role',
    executeLaunchCluster: 'Launch Corporate Cluster',
    deployingCluster: 'Deploying Nodes...',
    userWorkspaceTerminal: 'User Workspace Terminal',
    supervisingAllEmployees: 'Sabhi active employees ki supervision',
    displayingScopeStaff: 'Iss company ke active staff:',
    companyContextNode: 'Company Node',
    staffMemberIdentity: 'Staff Identity',
    securityAccessPassword: 'Access Password',
    workspaceBoundaryNode: 'Workspace Boundary',
    scopePermissions: 'Permissions',
    cascadeDeletionZone: 'Company Deletion Zone',
    deletionZoneDesc: 'Irreversible cloud cluster cleanups',
    selectCorporateTargetErase: 'Delete karne ke liye company chunen',
    eraseCorporateProfileNode: 'Erase Corporate Profile',
    wipingNode: 'Wiping Node...'
  },
  ar: {
    dashboard: 'لوحة القيادة',
    accounting: 'المحاسبة',
    chartOfAccounts: 'شجرة الحسابات',
    journalEntry: 'دفتر اليومية',
    generalLedger: 'الدفتر العام',
    bankReconciliation: 'التسوية البنكية',
    business: 'الأعمال',
    sales: 'المبيعات',
    purchases: 'المشتريات',
    inventory: 'المخزون',
    warehouses: 'المستودعات',
    expenses: 'المصروفات',
    eCommercePayouts: 'مدفوعات التجارة الإلكترونية',
    reports: 'التقارير',
    system: 'النظام',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    aiAssistant: 'مساعد الذكاء الاصطناعي',
    settingsPanel: 'لوحة الإعدادات',
    userProfileNode: 'ملف المستخدم',
    fullSignatureName: 'الاسم الكامل',
    accessAuthKey: 'مفتاح المرور',
    updateProfile: 'تحديث الملف الشخصي',
    interfaceLanguage: 'لغة النظام',
    selectLanguageDesc: 'اختر لغة التشغيل المفضلة:',
    askAiPlaceholder: 'طرح أسئلة مالية أو طلب تحليلات محاسبية...',
    clearChat: 'مسح المحادثة',
    aiDisclaimer: 'يتم إنشاء الإجابات بناءً على البيانات المالية الحالية.',
    manageCompanyFeatures: 'إدارة وتعديل ميزات الشركة',
    clickEditFeaturesDesc: 'انقر فوق "تعديل الميزات" لتشغيل أو إيقاف تشغيل الوحدات',
    companyName: 'اسم الشركة',
    companyId: 'معرف الشركة',
    actionOptions: 'خيارات الإجراء',
    editFeatures: 'تعديل الميزات',
    enterpriseControlCenter: 'مركز التحكم متعدد الشركات',
    enterpriseControlDesc: 'تكوين الوصول وتسلسل الأرقام وحدود المستخدمين',
    companyProfileTitle: 'عنوان ملف الشركة',
    officialContactEmail: 'البريد الإلكتروني الرسمي',
    taxNodeId: 'الرقم الضريبي (اختياري)',
    reportingBaseCurrency: 'العملة الأساسية',
    invoiceFormatPrefix: 'بادئة الفاتورة',
    initialNextIndex: 'التسلسل التالي',
    ecosystemCapabilities: 'تكوين ميزات النظام',
    bindInitialStaff: 'ربط الموظف الأولي (اختياري)',
    staffDisplayName: 'اسم الموظف',
    uniqueUsernameHandle: 'اسم المستخدم',
    securityLoginPassword: 'كلمة المرور',
    scopeLockedRole: 'الدور المحدد',
    executeLaunchCluster: 'إنشاء وإطلاق الشركة',
    deployingCluster: 'جاري الإنشاء...',
    userWorkspaceTerminal: 'محطة إدارة المستخدمين',
    supervisingAllEmployees: 'الإشراف على جميع الموظفين النشطين',
    displayingScopeStaff: 'عرض الموظفين المعينين في',
    companyContextNode: 'سياق الشركة',
    staffMemberIdentity: 'هوية الموظف',
    securityAccessPassword: 'كلمة المرور',
    workspaceBoundaryNode: 'عقدة النطاق',
    scopePermissions: 'الصلاحيات',
    cascadeDeletionZone: 'منطقة حذف الشركات',
    deletionZoneDesc: 'تنظيف دائم وغير قابل للاسترداد',
    selectCorporateTargetErase: 'حدد الشركة المراد حذفها',
    eraseCorporateProfileNode: 'حذف ملف الشركة',
    wipingNode: 'جاري الحذف...'
  },
  zh: {
    dashboard: '仪表板',
    accounting: '会计',
    chartOfAccounts: '科目表',
    journalEntry: '普通日记账',
    generalLedger: '总分类账',
    bankReconciliation: '银行调节表',
    business: '业务',
    sales: '销售',
    purchases: '采购',
    inventory: '库存',
    warehouses: '仓库',
    expenses: '费用',
    eCommercePayouts: '电商结算',
    reports: '报告',
    system: '系统',
    settings: '设置',
    logout: '退出登录',
    aiAssistant: 'AI 助手',
    settingsPanel: '设置面板',
    userProfileNode: '用户个人资料',
    fullSignatureName: '全名',
    accessAuthKey: '访问授权密钥',
    updateProfile: '更新个人资料',
    interfaceLanguage: '界面语言',
    selectLanguageDesc: '选择首选系统语言：',
    askAiPlaceholder: '询问财务问题或请求会计分析...',
    clearChat: '清空聊天',
    aiDisclaimer: 'AI 响应基于实时账簿数据生成。',
    manageCompanyFeatures: '管理和编辑公司功能',
    clickEditFeaturesDesc: '点击“编辑功能”以开启/关闭模块',
    companyName: '公司名称',
    companyId: '公司 ID',
    actionOptions: '操作选项',
    editFeatures: '编辑功能',
    enterpriseControlCenter: '企业多公司控制中心',
    enterpriseControlDesc: '配置系统访问权限、编号顺序和用户边界',
    companyProfileTitle: '公司资料标题',
    officialContactEmail: '官方联系邮箱',
    taxNodeId: '税号 / NTN ID（可选）',
    reportingBaseCurrency: '基础货币',
    invoiceFormatPrefix: '发票前缀',
    initialNextIndex: '初始索引顺序',
    ecosystemCapabilities: '系统功能配置',
    bindInitialStaff: '绑定初始员工身份（可选）',
    staffDisplayName: '员工显示名称',
    uniqueUsernameHandle: '唯一用户名',
    securityLoginPassword: '登录密码',
    scopeLockedRole: '锁定角色分配',
    executeLaunchCluster: '执行并启动公司',
    deployingCluster: '正在部署...',
    userWorkspaceTerminal: '用户工作区管理终端',
    supervisingAllEmployees: '监督所有公司的在职员工',
    displayingScopeStaff: '显示特定公司的员工：',
    companyContextNode: '公司上下文节点',
    staffMemberIdentity: '员工身份',
    securityAccessPassword: '安全访问密码',
    workspaceBoundaryNode: '边界锁定节点',
    scopePermissions: '权限范围',
    cascadeDeletionZone: '基础设施级联删除区',
    deletionZoneDesc: '不可逆的云端清理',
    selectCorporateTargetErase: '选择要清除的公司',
    eraseCorporateProfileNode: '清除公司资料',
    wipingNode: '正在清除...'
  },
  es: {
    dashboard: 'Panel de Control',
    accounting: 'Contabilidad',
    chartOfAccounts: 'Plan de Cuentas',
    journalEntry: 'Diario General',
    generalLedger: 'Libro Mayor',
    bankReconciliation: 'Conciliación Bancaria',
    business: 'Negocio',
    sales: 'Ventas',
    purchases: 'Compras',
    inventory: 'Inventario',
    warehouses: 'Almacenes',
    expenses: 'Gastos',
    eCommercePayouts: 'Pagos E-Commerce',
    reports: 'Informes',
    system: 'Sistema',
    settings: 'Configuración',
    logout: 'Cerrar Sesión',
    aiAssistant: 'Asistente IA',
    settingsPanel: 'Panel de Configuración',
    userProfileNode: 'Perfil de Usuario',
    fullSignatureName: 'Nombre Completo',
    accessAuthKey: 'Clave de Autorización',
    updateProfile: 'Actualizar Perfil',
    interfaceLanguage: 'Idioma de Interfaz',
    selectLanguageDesc: 'Seleccione el idioma preferido del sistema:',
    askAiPlaceholder: 'Haga preguntas financieras o solicite informes contables...',
    clearChat: 'Limpiar Chat',
    aiDisclaimer: 'Las respuestas de IA se generan según los datos contables activos.',
    manageCompanyFeatures: 'Gestionar y editar funciones de empresa',
    clickEditFeaturesDesc: 'Haga clic en "Editar funciones" para activar/desactivar módulos',
    companyName: 'Nombre de la Empresa',
    companyId: 'ID de la Empresa',
    actionOptions: 'Opciones de Acción',
    editFeatures: 'Editar Funciones',
    enterpriseControlCenter: 'Centro de Control Multiempresa',
    enterpriseControlDesc: 'Configure firmas de acceso, secuencias numéricas y límites de usuarios',
    companyProfileTitle: 'Título del Perfil',
    officialContactEmail: 'Correo Oficial',
    taxNodeId: 'ID Fiscal (Opcional)',
    reportingBaseCurrency: 'Moneda Base',
    invoiceFormatPrefix: 'Prefijo de Factura',
    initialNextIndex: 'Secuencia Inicial',
    ecosystemCapabilities: 'Configuración de Capacidades',
    bindInitialStaff: 'Vincular Personal Inicial (Opcional)',
    staffDisplayName: 'Nombre del Personal',
    uniqueUsernameHandle: 'Nombre de Usuario',
    securityLoginPassword: 'Contraseña de Seguridad',
    scopeLockedRole: 'Asignación de Rol',
    executeLaunchCluster: 'Ejecutar y Lanzar Empresa',
    deployingCluster: 'Desplegando...',
    userWorkspaceTerminal: 'Terminal de Gestión de Usuarios',
    supervisingAllEmployees: 'Supervisando a todos los empleados activos',
    displayingScopeStaff: 'Mostrando personal de',
    companyContextNode: 'Nodo de Empresa',
    staffMemberIdentity: 'Identidad del Personal',
    securityAccessPassword: 'Contraseña de Acceso',
    workspaceBoundaryNode: 'Nodo de Límite',
    scopePermissions: 'Permisos',
    cascadeDeletionZone: 'Zona de Eliminación de Infraestructura',
    deletionZoneDesc: 'Limpieza irreversible en la nube',
    selectCorporateTargetErase: 'Seleccionar empresa a eliminar',
    eraseCorporateProfileNode: 'Eliminar Empresa',
    wipingNode: 'Eliminando...'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('preferred_language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred_language', lang);
  };

  const t = (key: string): string => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    if (translations['en'] && translations['en'][key]) {
      return translations['en'][key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};